/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.table.DefaultTableModel;
import controller.AdminController;
import controller.AdminController;
import model.Doctor;
import java.util.List;

/**
 *
 * @author Adam
 */
public class AdminPanel extends javax.swing.JFrame {

    private final AdminController controller = new AdminController();

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
        updateDashboardStats();
        loadDoctorTable();
    }

    private void loadDoctorTable() {
        // 1. Define Table Model structure
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"ID", "Name", "Specialization", "Age", "Contact", "Login ID"});

        try {
            // 2. Fetch data from the controller
            List<Doctor> doctors = controller.getAllDoctors(); // Already defined in AdminController

            // 3. Populate rows
            for (Doctor d : doctors) {
                model.addRow(new Object[]{
                    d.getId(),
                    d.getName(),
                    d.getSpecialization(),
                    d.getAge(),
                    d.getContactInfo(),
                    d.getLoginId()
                });
            }

            // 4. Set the model to the JTable
            tblDoctors.setModel(model);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading doctor list: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void updateDashboardStats() {
        try {
            // 1. Get stats from the Controller
            java.util.Map<String, Integer> stats = controller.getDashboardStatistics();

            // 2. Update the JLabels (You may need to change the label names below to match your design)
            // Example Labels based on your controller keys:
            if (stats.containsKey("Waiting")) {
                lblWaitingCount.setText("Waiting : " + String.valueOf(stats.get("Waiting")));
            }
            if (stats.containsKey("In-treatment")) {
                lblInTreatmentCount.setText("In-Treatment : " + String.valueOf(stats.get("In-treatment")));
            }
            if (stats.containsKey("Complete")) {
                lblCompleteCount.setText("Completed :" + String.valueOf(stats.get("Complete")));
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading dashboard statistics: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWaitingCount = new javax.swing.JLabel();
        lblInTreatmentCount = new javax.swing.JLabel();
        lblCompleteCount = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDoctors = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuRegisterDoctor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWaitingCount.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblWaitingCount.setText("Waiting : ");

        lblInTreatmentCount.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblInTreatmentCount.setForeground(new java.awt.Color(0, 204, 0));
        lblInTreatmentCount.setText("In - treatment : ");
        lblInTreatmentCount.setToolTipText("");

        lblCompleteCount.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblCompleteCount.setForeground(new java.awt.Color(0, 153, 255));
        lblCompleteCount.setText("Complete : ");

        tblDoctors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Specialization", "Age", "Contact", "Login ID"
            }
        ));
        jScrollPane2.setViewportView(tblDoctors);

        jButton1.setText("Manage Appointment");

        jButton2.setText("Manage Doctor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Action");

        menuRegisterDoctor.setText("Register New Doctor");
        menuRegisterDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegisterDoctorActionPerformed(evt);
            }
        });
        jMenu1.add(menuRegisterDoctor);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblWaitingCount)
                .addGap(121, 121, 121)
                .addComponent(lblInTreatmentCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(lblCompleteCount)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton1)
                .addGap(169, 169, 169)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWaitingCount)
                    .addComponent(lblInTreatmentCount)
                    .addComponent(lblCompleteCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegisterDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegisterDoctorActionPerformed
        // Launch the dedicated registration form
        new view.RegisterDoctorForm().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_menuRegisterDoctorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCompleteCount;
    private javax.swing.JLabel lblInTreatmentCount;
    private javax.swing.JLabel lblWaitingCount;
    private javax.swing.JMenuItem menuRegisterDoctor;
    private javax.swing.JTable tblDoctors;
    // End of variables declaration//GEN-END:variables
}
