/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.table.DefaultTableModel;

import controller.AdminController;
import model.Doctor;
import java.util.List;

/**
 *
 * @author Adam
 */
public class AdminPanel extends javax.swing.JFrame {

    private final AdminController controller = new AdminController();

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
        updateDashboardStats();
        loadDoctorTable();
    }

    private void loadDoctorTable() {
        // 1. Define Table Model structure for Appointments
        DefaultTableModel model = new DefaultTableModel();
        // We are now showing Appointment data, not Doctor data
        model.setColumnIdentifiers(new Object[]{"Appointment ID", "Patient Name", "Diagnosis", "Status"});

        try {
            // 2. Fetch data from the controller for 'in-treatment' appointments
            java.util.List<java.util.Map<String, Object>> appointments = controller.getInTreatmentAppointmentsForAdmin();

            // 3. Populate rows
            for (java.util.Map<String, Object> appointment : appointments) {
                model.addRow(new Object[]{
                    appointment.get("appointment_id"),
                    appointment.get("patient_name"),
                    appointment.get("diagnosis"),
                    appointment.get("status")
                });
            }

            // 4. Set the model to the JTable (assuming the JTable variable is still named tblDoctors)
            tblDoctors.setModel(model);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading active appointment list: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void updateDashboardStats() {
        try {
            // 1. Get stats from the Controller
            java.util.Map<String, Integer> stats = controller.getDashboardStatistics();

            // 2. Update the JLabels (You may need to change the label names below to match your design)
            // Example Labels based on your controller keys:
            if (stats.containsKey("Waiting")) {
                lblWaitingCount.setText("Waiting : " + String.valueOf(stats.get("Waiting")));
            }
            if (stats.containsKey("In-treatment")) {
                lblInTreatmentCount2.setText("In-Treatment : " + String.valueOf(stats.get("In-treatment")));
            }
            if (stats.containsKey("Completed")) {
                lblCompleteCount.setText("Completed :" + String.valueOf(stats.get("Completed")));
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading dashboard statistics: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInTreatmentCount = new javax.swing.JLabel();
        lblWaitingCount = new javax.swing.JLabel();
        lblCompleteCount = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDoctors = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblInTreatmentCount2 = new javax.swing.JLabel();
        btnCompleteAppointment = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logoutItem = new javax.swing.JMenuItem();

        lblInTreatmentCount.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblInTreatmentCount.setForeground(new java.awt.Color(0, 204, 0));
        lblInTreatmentCount.setText("In - treatment : ");
        lblInTreatmentCount.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWaitingCount.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblWaitingCount.setText("Waiting : ");

        lblCompleteCount.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblCompleteCount.setForeground(new java.awt.Color(0, 153, 255));
        lblCompleteCount.setText("Complete : ");

        tblDoctors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IDAppointment ID", "Patient Name", "Diagnosis", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblDoctors);

        jButton1.setText("Manage Appointment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Doctor Management");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblInTreatmentCount2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblInTreatmentCount2.setForeground(new java.awt.Color(0, 204, 51));
        lblInTreatmentCount2.setText("In Treatment");

        btnCompleteAppointment.setText("Complete");
        btnCompleteAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteAppointmentActionPerformed(evt);
            }
        });

        jMenu1.setText("Action");

        logoutItem.setText("LogOut");
        logoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutItemActionPerformed(evt);
            }
        });
        jMenu1.add(logoutItem);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblWaitingCount)
                .addGap(141, 141, 141)
                .addComponent(lblInTreatmentCount2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCompleteCount)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCompleteAppointment)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWaitingCount)
                    .addComponent(lblCompleteCount)
                    .addComponent(lblInTreatmentCount2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompleteAppointment)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AppointmentManagementForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutItemActionPerformed
        new MainMenu().setVisible(true);
        dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_logoutItemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new DoctorManagementForm().setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCompleteAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteAppointmentActionPerformed
        // 1. Get the selected row index
        int selectedRow = tblDoctors.getSelectedRow();

        if (selectedRow == -1) {
            // No row selected
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an appointment from the table to complete.", "Selection Required", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Retrieve the Appointment ID from the selected row.
            // The Appointment ID is in the first column (index 0). 
            // We cast it to Integer, as it was added as an Integer object to the model.
            Integer appointmentId = (Integer) tblDoctors.getValueAt(selectedRow, 0);

            // Confirmation dialog for the Admin
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to mark Appointment ID " + appointmentId + " as Completed?",
                    "Confirm Completion", javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                // 3. Call the DAO method to update the status to "Completed"
                dao.AppointmentDAO appointmentDAO = new dao.AppointmentDAO(); // Re-initialize or use your existing instance
                boolean success = appointmentDAO.updateAppointmentStatus(appointmentId, "Completed");

                if (success) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Appointment " + appointmentId + " successfully marked as Completed.");
                    // 4. Refresh the table to show the updated list (the row should disappear if loadDoctorTable() filters for 'in-treatment')
                    loadDoctorTable();
                    updateDashboardStats();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to complete appointment.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error processing completion: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnCompleteAppointmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompleteAppointment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCompleteCount;
    private javax.swing.JLabel lblInTreatmentCount;
    private javax.swing.JLabel lblInTreatmentCount2;
    private javax.swing.JLabel lblWaitingCount;
    private javax.swing.JMenuItem logoutItem;
    private javax.swing.JTable tblDoctors;
    // End of variables declaration//GEN-END:variables
}
