/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AppointmentDAO;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adam
 */
public class DoctorPortal extends javax.swing.JFrame {

    private final AppointmentDAO appointmentDAO = new AppointmentDAO(); // Instantiate DAO
    private int loggedInDoctorId; // New field to store the ID

    /**
     * Creates new form DoctorPortal
     */
    public DoctorPortal(int doctorId) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.loggedInDoctorId = doctorId; // Store the ID for later use (e.g., updating record)
        refreshTable(); // Now calls the simpler refreshTable without arguments
    }

// Update the refreshTable method (it no longer needs the doctorId argument)
    private void refreshTable() {
        int doctorId = this.loggedInDoctorId;

        // Use AppointmentDAO to get detailed appointment data for today
        List<Map<String, Object>> appointmentDetails = null;

        try {
            // New DAO method to get active appointments (waiting/in-treatment)
            appointmentDetails = appointmentDAO.getTodaysActiveAppointmentsByDoctor(doctorId);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading appointments: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return; // Stop execution on error
        }

        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Map<String, Object> appointment : appointmentDetails) {
            // Populate all 5 columns: ID, Name, Age, Diagnosis, Status
            model.addRow(new Object[]{
                // FIX: Column 0 MUST be the Appointment ID (used for updates)
                appointment.get("appointment_id"),
                appointment.get("patient_name"),
                appointment.get("patient_age"),
                appointment.get("status"),
                appointment.get("date"),
                
                    
                    
            });
        }

        // Auto-select the first row after refresh
        if (model.getRowCount() > 0) {
            tblPatients.setRowSelectionInterval(0, 0);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiagnosis = new javax.swing.JTextArea();
        btnUpdate = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logoutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Status", "date"
            }
        ));
        jScrollPane1.setViewportView(tblPatients);
        if (tblPatients.getColumnModel().getColumnCount() > 0) {
            tblPatients.getColumnModel().getColumn(4).setPreferredWidth(200);
            tblPatients.getColumnModel().getColumn(4).setMaxWidth(300);
        }

        jLabel2.setText("Doctor's Notes / Diagnosis:");

        txtDiagnosis.setColumns(20);
        txtDiagnosis.setRows(5);
        jScrollPane2.setViewportView(txtDiagnosis);

        btnUpdate.setText("Update Patient Record");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jMenu1.setText("Action");

        logoutItem.setText("LogOut");
        logoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutItemActionPerformed(evt);
            }
        });
        jMenu1.add(logoutItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(243, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // 1. Check if a row is selected
        int selectedRow = tblPatients.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please click on a patient in the table first!");
            return;
        }

        try {
            // 2. Get Data: Column 0 is now the Appointment ID
            int appointmentId = Integer.parseInt(tblPatients.getValueAt(selectedRow, 0).toString());
            String newDiagnosis = txtDiagnosis.getText();

            // 3. Update in Database: Use the specific method to move the status to 'in-treatment'
            // This is triggered when the doctor starts working on the diagnosis.
            String status = "in-treatment";
            boolean success = appointmentDAO.updateDiagnosisAndStartTreatment(appointmentId, status,newDiagnosis);

            if (success) {
                JOptionPane.showMessageDialog(this, "Record Updated! Patient status set to In-Treatment.");
            } else {
                JOptionPane.showMessageDialog(this, "Update Failed! Check database connection or record existence.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // 4. Refresh and clear
            refreshTable();
            txtDiagnosis.setText(""); // Clear box

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error processing Appointment ID.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } 

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void logoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutItemActionPerformed
    new MainMenu().setVisible(true);
    dispose();
    }//GEN-LAST:event_logoutItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { //direct testing only, later when we finalize the program we need to delete this main
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorPortal(1).setVisible(true); // '1' for testing

            }

        }
        );

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem logoutItem;
    private javax.swing.JTable tblPatients;
    private javax.swing.JTextArea txtDiagnosis;
    // End of variables declaration//GEN-END:variables
}
