/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Adam
 */
public class ReceptionForm extends javax.swing.JFrame {

    /**
     * Creates new form ReceptionForm
     */
    public ReceptionForm() {
        initComponents();
        loadDoctors();
    }
    // Helper method to fill the dropdown
    private void loadDoctors() {
        dao.DoctorDAO docDao = new dao.DoctorDAO();
        java.util.List<model.Doctor> doctors = docDao.getAllDoctors();
        
        for (model.Doctor d : doctors) {
            comboDoctor.addItem(d); // Adds the Doctor object to the box
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        comboDoctor = new javax.swing.JComboBox<>();
        comboTimeSlot = new javax.swing.JComboBox<>();
        btnBook = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtICNumber = new javax.swing.JTextField();
        txtAppointmentDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Age");

        jLabel3.setText("Select Doctor");

        jLabel4.setText("Time Slot");

        txtName.setToolTipText("");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        comboTimeSlot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00-10:00", "10:00-11:00", "11:00-12:00" }));

        btnBook.setText("Book Appointment");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        jLabel5.setText("IC Number (Unique):");

        txtICNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtICNumberFocusLost(evt);
            }
        });

        txtAppointmentDate.setText("YYYY-MM-DD");
        txtAppointmentDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAppointmentDateFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBook)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(12, 12, 12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboTimeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(251, 251, 251))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                        .addComponent(txtICNumber)))
                                .addGap(200, 200, 200))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtICNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(comboTimeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnBook)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
       try {
            // 1. Get Data from Form
            String name = txtName.getText();
            String icNumber = txtICNumber.getText().trim(); // <--- GET IC HERE
            String dateText = txtAppointmentDate.getText().trim(); // <--- GET DATE HERE
            
            // Validate inputs
            if(name.isEmpty() || icNumber.isEmpty() || dateText.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please fill all fields!");
                return;
            }
            
            // Parse Age
            int age = Integer.parseInt(txtAge.getText());
            
            // Get the selected Doctor object and Time Slot
            model.Doctor selectedDoc = (model.Doctor) comboDoctor.getSelectedItem();
            String timeSlot = comboTimeSlot.getSelectedItem().toString();
            
            // 2. Save Patient First
            // We need to check if the patient already exists to avoid duplicates
            dao.PatientDAO patientDao = new dao.PatientDAO();
            model.Patient existing = patientDao.getPatientByIC(icNumber);
            
            int patientId;
            
            if (existing != null) {
                // If patient exists, use their existing ID
                patientId = existing.getId();
            } else {
                // If new patient, create them (MAKE SURE PatientDAO handles IC Number!)
                // Note: You might need to update your Patient Model constructor to accept IC
                model.Patient newPatient = new model.Patient(0, name, age, icNumber, "Checkup", "Waiting");
                // You need to update your PatientDAO.addPatient method to save the IC number too!
                patientId = patientDao.addPatient(newPatient); 
            }
            
            if (patientId != -1) {
                // 3. Save Appointment using the variables (NOT hardcoded strings)
                dao.AppointmentDAO apptDao = new dao.AppointmentDAO();
                
                // FIX: Use 'dateText' instead of "2025-12-01"
                apptDao.bookAppointment(patientId, selectedDoc.getId(), dateText, timeSlot);
                
                javax.swing.JOptionPane.showMessageDialog(this, "Success! Appointment Booked.");
                
                // Clear fields
                txtName.setText("");
                txtAge.setText("");
                txtICNumber.setText("");
                txtName.setEnabled(true);
                txtAge.setEnabled(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error saving patient.");
            }
            
        } catch (NumberFormatException e) {
             javax.swing.JOptionPane.showMessageDialog(this, "Age must be a number.");
        } catch (Exception e) {
             javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
             e.printStackTrace();
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void txtICNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtICNumberFocusLost
    String ic = txtICNumber.getText().trim();
        if (ic.isEmpty()) return; // Don't check if empty

    dao.PatientDAO dao = new dao.PatientDAO();
    model.Patient p = dao.getPatientByIC(ic); // Call Phase 2 method

    if (p != null) {
        // Found! Auto-fill fields
        javax.swing.JOptionPane.showMessageDialog(this, "Patient Found: " + p.getName());
        txtName.setText(p.getName());
        txtAge.setText(String.valueOf(p.getAge()));
        
        // Lock fields so staff don't accidentally change them
        txtName.setEnabled(false);
        txtAge.setEnabled(false);
    } else {
        // Not found? Clear fields for new entry
        txtName.setEnabled(true);
        txtAge.setEnabled(true);
    }
    }//GEN-LAST:event_txtICNumberFocusLost

    private void txtAppointmentDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAppointmentDateFocusLost
        updateAvailableSlots();
    }//GEN-LAST:event_txtAppointmentDateFocusLost
// Define your clinic hours here
private final String[] ALL_SLOTS = {"09:00-10:00", "10:00-11:00", "11:00-12:00", "14:00-15:00", "15:00-16:00"};

private void updateAvailableSlots() {
    try {
        // 1. Check if Doctor and Date are filled
        if (comboDoctor.getSelectedItem() == null || txtAppointmentDate.getText().isEmpty()) {
            return;
        }

        // 2. Get inputs
        model.Doctor selectedDoc = (model.Doctor) comboDoctor.getSelectedItem();
        String dateText = txtAppointmentDate.getText().trim();

        // 3. Get BUSY slots from DB (Call Phase 3 method)
        dao.AppointmentDAO dao = new dao.AppointmentDAO();
        java.util.Set<String> busySlots = dao.getBookedTimeSlots(selectedDoc.getId(), dateText);

        // 4. Reset and Fill Dropdown
        comboTimeSlot.removeAllItems();
        
        for (String slot : ALL_SLOTS) {
            if (!busySlots.contains(slot)) {
                // Only add the slot if it is NOT in the busy list
                comboTimeSlot.addItem(slot);
            }
        }
        
    } catch (Exception e) {
        // If date format is wrong, just ignore for now
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JComboBox<model.Doctor> comboDoctor;
    private javax.swing.JComboBox<String> comboTimeSlot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextField txtICNumber;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
