/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Adam
 */
public class ReceptionForm extends javax.swing.JFrame {

    /**
     * Creates new form ReceptionForm
     */
    public ReceptionForm() {
        initComponents();
        loadDoctors();
    }

    // Helper method to fill the dropdown
    private void loadDoctors() {
        dao.DoctorDAO docDao = new dao.DoctorDAO();
        java.util.List<model.Doctor> doctors = docDao.getAllDoctors();

        for (model.Doctor d : doctors) {
            comboDoctor.addItem(d); // Adds the Doctor object to the box
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        comboDoctor = new javax.swing.JComboBox<>();
        comboTimeSlot = new javax.swing.JComboBox<>();
        btnBook = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtICNumber = new javax.swing.JTextField();
        txtAppointmentDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtContact_info = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name : ");

        jLabel2.setText("Age : ");

        jLabel3.setText("Select Doctor");

        jLabel4.setText("Time Slot : ");

        txtName.setToolTipText("");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        comboTimeSlot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00-10:00", "10:00-11:00", "11:00-12:00" }));

        btnBook.setText("Book Appointment");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        jLabel5.setText("IC Number :");

        txtICNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtICNumberFocusLost(evt);
            }
        });

        txtAppointmentDate.setText("YYYY-MM-DD");
        txtAppointmentDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAppointmentDateFocusLost(evt);
            }
        });

        jLabel6.setText("Gender :");

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel7.setText("Contact Info : ");

        jLabel8.setText("Appointment Date : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(9, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtICNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtName))
                    .addComponent(txtContact_info, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboTimeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnBook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtICNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtContact_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(comboDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboTimeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBook)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        try {
            // 1. Get Data from Form
            String name = txtName.getText();
            String age = txtAge.getText();
            String gender = cbGender.getSelectedItem().toString();
            String contact_info = txtContact_info.getText();

            String icNumber = txtICNumber.getText().trim();
            String dateText = txtAppointmentDate.getText().trim();

            // Validate inputs
            if (name.isEmpty() || age.isEmpty() || contact_info.isEmpty() || icNumber.isEmpty() || dateText.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please fill all fields!");
                return;
            }
            int parsed_age = Integer.parseInt(age);

            // Get the selected Doctor object and Time Slot
            model.Doctor selectedDoc = (model.Doctor) comboDoctor.getSelectedItem();
            String timeSlot = comboTimeSlot.getSelectedItem().toString();

            // 2. Check Database for Existing Patient
            dao.PatientDAO patientDao = new dao.PatientDAO();
            model.Patient existing = patientDao.getPatientByIC(icNumber);

            int patientId;

            if (existing != null) {
                // CASE A: Patient found in DB -> Use their ID
                System.out.println("Patient found: ID " + existing.getId()); // Debug print
                patientId = existing.getId();
            } else {
                // CASE B: New Patient (or lookup failed) -> Create New
                System.out.println("Patient not found, creating new..."); // Debug print

                // --- FIX IS HERE: PASS 'icNumber' TO THE CONSTRUCTOR ---
                // Ensure your Patient.java (Model) constructor accepts these arguments!
                model.Patient newPatient = new model.Patient(0, name, parsed_age, gender, contact_info, icNumber, "Checkup", "Waiting");

                patientId = patientDao.addPatient(newPatient);
            }

            // 3. Check result
            if (patientId != -1) {
                // Save Appointment
                dao.AppointmentDAO apptDao = new dao.AppointmentDAO();
                apptDao.bookAppointment(patientId, selectedDoc.getId(), dateText, timeSlot);

                javax.swing.JOptionPane.showMessageDialog(this, "Success! Appointment Booked.");

                // Clear fields
                txtName.setText("");
                txtAge.setText("");
                txtICNumber.setText("");
                txtName.setEnabled(true);
                txtAge.setEnabled(true);
            } else {
                // If we get here, the DB rejected the INSERT (likely duplicate IC or missing data)
                javax.swing.JOptionPane.showMessageDialog(this, "Error saving patient. (Check if IC is unique or DB connection)");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Age must be a number.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void txtICNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtICNumberFocusLost
        String ic = txtICNumber.getText().trim();
        if (ic.isEmpty()) {
            return; // Don't check if empty
        }
        dao.PatientDAO dao = new dao.PatientDAO();
        model.Patient p = dao.getPatientByIC(ic); // Call Phase 2 method

        if (p != null) {
            // Found! Auto-fill fields
            javax.swing.JOptionPane.showMessageDialog(this, "Patient Found: " + p.getName());
            txtName.setText(p.getName());
            txtAge.setText(String.valueOf(p.getAge()));
            cbGender.setSelectedItem(p.getGender());
            txtContact_info.setText(p.getContactInfo());
            

            // Lock fields so staff don't accidentally change them
            txtName.setEnabled(false);
            txtAge.setEnabled(false);
            txtContact_info.setEnabled(false);
            cbGender.setEnabled(false);
        } else {
            // Not found? Clear fields for new entry
            txtName.setEnabled(true);
            txtAge.setEnabled(true);
        }
    }//GEN-LAST:event_txtICNumberFocusLost

    private void txtAppointmentDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAppointmentDateFocusLost
        updateAvailableSlots();
    }//GEN-LAST:event_txtAppointmentDateFocusLost
// Define your clinic hours here
    private final String[] ALL_SLOTS = {"09:00-10:00", "10:00-11:00", "11:00-12:00", "14:00-15:00", "15:00-16:00"};

    private void updateAvailableSlots() {
        try {
            // 1. Check if Doctor and Date are filled
            if (comboDoctor.getSelectedItem() == null || txtAppointmentDate.getText().isEmpty()) {
                return;
            }

            // 2. Get inputs
            model.Doctor selectedDoc = (model.Doctor) comboDoctor.getSelectedItem();
            String dateText = txtAppointmentDate.getText().trim();

            // 3. Get BUSY slots from DB (Call Phase 3 method)
            dao.AppointmentDAO dao = new dao.AppointmentDAO();
            java.util.Set<String> busySlots = dao.getBookedTimeSlots(selectedDoc.getId(), dateText);

            // 4. Reset and Fill Dropdown
            comboTimeSlot.removeAllItems();

            for (String slot : ALL_SLOTS) {
                if (!busySlots.contains(slot)) {
                    // Only add the slot if it is NOT in the busy list
                    comboTimeSlot.addItem(slot);
                }
            }

        } catch (Exception e) {
            // If date format is wrong, just ignore for now
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<model.Doctor> comboDoctor;
    private javax.swing.JComboBox<String> comboTimeSlot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextField txtContact_info;
    private javax.swing.JTextField txtICNumber;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
